name: submon
description: Submission Managing App

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0-beta04+23

environment:
  sdk: ">=2.14.4 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  audioplayers: ^0.20.1
  sqflite: ^2.0.2+1
  animations: ^2.0.2
  event_bus: ^2.0.0
  flutter_platform_widgets: ^1.20.0
  package_info_plus: ^1.4.2
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.14
  google_sign_in: ^5.3.1
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.2
  flutter_dotenv: ^5.0.2
  flutter_slidable: ^1.2.0
  url_launcher: ^6.1.1
  camera: ^0.9.4+22
  flutter_linkify: ^5.0.2
  path_provider: ^2.0.10
  flutter_exif_rotation: ^0.5.1
  time_picker_widget: ^1.0.0+10
  wakelock: ^0.6.1+2
  fullscreen: ^1.0.3
  flutter_dnd: ^0.1.4+1
  permission_handler: ^9.2.0
  fluttertoast: ^8.0.9
  collection: ^1.16.0
  vector_math: ^2.1.2
  path: ^1.8.1
  in_app_review: ^2.0.4
  device_info_plus: ^3.2.3
  share_plus: ^4.0.4

  googleapis: ^8.1.0
  googleapis_auth: ^1.3.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.4
  google_mobile_ads: ^1.2.0

  firebase_core: ^1.16.0
  firebase_crashlytics: ^2.7.2
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  firebase_analytics: ^9.1.7
  firebase_dynamic_links: ^4.2.2
  firebase_performance: ^0.8.0+11
  cloud_functions: ^3.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/img/
    - assets/audio/
    - assets/vector/
    - .env
    - assets/google_fonts/Murecho/
    - assets/google_fonts/Play/
    - assets/google_fonts/B612_Mono/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Murecho
      fonts:
        - asset: assets/google_fonts/Murecho/Murecho-Regular.ttf
        - asset: assets/google_fonts/Murecho/Murecho-Bold.ttf
          weight: 700
    - family: Play
      fonts:
        - asset: assets/google_fonts/Play/Play-Bold.ttf
    - family: B612 Mono
      fonts:
        - asset: assets/google_fonts/B612_Mono/B612Mono-Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
